services:
  - type: web
    name: jollof-palace-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: jollof-palace-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false

databases:
  - name: jollof-palace-db
    databaseName: jollof_palace
    user: jollof_admin
    plan: starter